name: anime_dx
description: "Minimal yet feature-rich Anime/Manga Client"
publish_to: "none"
version: 2.1.4+4

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.1
  flutter_riverpod: ^3.3.1
  flex_color_scheme: ^8.4.0
  logger: ^2.8.0
  path: ^1.9.1
  path_provider: ^2.1.5
  isar_community: 3.3.2
  isar_community_flutter_libs: 3.3.2
  flutter_secure_storage: ^10.3.1
  flutter_web_auth_2:
    git:
      url: https://github.com/aayush2622/flutter_web_auth.git
      path: flutter_web_auth_2
  anymex_extension_runtime_bridge:
    path: packages/anymex_extension_bridge
  byte_me:
    path: packages/byte_me
  commentum_client:
    path: packages/commentum_client
  media_kit:
    git:
        url: https://github.com/Predidit/media-kit.git
        ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
        path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./libs/universal/media_kit_libs_video
  get: ^4.7.3
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  volume_controller: ^3.4.4
  screen_brightness: ^2.1.7
  http: ^1.6.0
  flutter_inappwebview:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      path: flutter_inappwebview
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  screenshot: ^3.0.0
  window_manager: ^0.5.1
  flutter_single_instance: ^1.7.0
  url_launcher: ^6.3.0
  html: ^0.15.7
  flutter_svg: ^2.2.4
  dynamic_color: 1.8.1
  permission_handler: 12.0.3
  file_picker: ^8.1.4
  encrypt: ^5.0.3
  android_intent_plus: ^6.0.0
  open_file: ^3.5.11
  device_info_plus: ^12.4.0
  package_info_plus: ^8.3.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.2
  collection: ^1.19.1
  app_links: ^6.4.1
  wakelock_plus: ^1.3.3
  flutter_markdown_plus: ^1.0.12
  palette_generator: ^0.3.3+7
  skeletonizer: ^2.1.3
  flutter_discord_rpc_fork:
    git:
      url: https://github.com/kodjodevf/flutter-discord-rpc.git
      ref: update_frb
  rhttp: ^0.18.0
  intl: ^0.20.2
  local_auth: ^3.0.1
  crypto: ^3.0.3
  flutter_device_apps: ^0.8.1
  better_player_plus: ^1.0.8

dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/EchoEllet/flutter_secure_storage.git
      path: flutter_secure_storage_linux
      ref: feat/linux-rewrite
  flutter_inappwebview:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      path: flutter_inappwebview
  flutter_inappwebview_linux:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      path: flutter_inappwebview_linux
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_android_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: main
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./libs/windows/media_kit_libs_windows_video
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 78d4cce7b49d5b6b918f78b18ec1fbb7c400b9da
      path: ./libs/macos/media_kit_libs_macos_video

  libtorrent_flutter:
    path: packages/anymex_extension_bridge/packages/libtorrent_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community_generator: 3.3.2
  package_rename: ^1.10.1
  inno_bundle: ^0.11.2
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.15.1

flutter:
  uses-material-design: true

inno_bundle:
  id: 17cd6e7b-cedc-43b7-86b1-4de6ab23dd4d
  name: ShonenX
  installer_icon: assets/images/installer.ico
  description: Anilist & MAL Client with extension support, for Anime lovers.
  publisher: roshancodespace
  url: https://github.com/roshancodespace/shonenx
  support_url: https://github.com/roshancodespace/shonenx/issues
  updates_url: https://github.com/roshancodespace/shonenx/releases
  languages:
    - english
  license_file: LICENSE
  admin: false
